name: global_event_bus
description: A high-performance, type-safe global event bus system for Flutter applications with priority support, batch processing, comprehensive logging, and visual debugging tools.
version: 1.3.0
homepage: https://github.com/pedro-pei-me/global_event_bus
repository: https://github.com/pedro-pei-me/global_event_bus
issue_tracker: https://github.com/pedro-pei-me/global_event_bus/issues


environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.22.0
